=== DevComPack/setupmaker/dev/schemas/izpack-langpack.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="langpack" type="langpacktype" />

<xs:complexType name="langpacktype">
	<xs:sequence>
		<xs:element name="str" type="strtype" minOccurs="1" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="strtype">
	<xs:attribute type="xs:string" name="id" />
	<xs:attribute type="xs:string" name="txt" />
</xs:complexType>

</xs:schema>

=== DevComPack/setupmaker/res/langpacks/ita.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="yes" ?>

<!-- The Italian langpack -->

<langpack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../schemas/izpack-langpack.xsd">

    <!-- Heading messages START -->
    <str id="CheckedHelloPanel.headline" txt="Benvenuti"/>
    <str id="CompilePanel.headline" txt="Compila Sorgenti Java"/>
    <str id="ConditionalUserInputPanel.headline" txt="Dati Utente"/>
    <str id="ExtendedInstallPanel.headline" txt="Installazione e Configurazione"/>
    <str id="FinishPanel.headline" txt="Installatione Completata"/>
    <str id="HelloPanel.headline" txt="Benvenuto"/>
    <str id="HTMLInfoPanel.headline" txt="Informazioni"/>
    <str id="HTMLLicencePanel.headline" txt="Accordo di Licenza"/>
    <str id="ImgPacksPanel.headline" txt="Seleziona Pacchetti di Installazione"/>
    <str id="InfoPanel.headline" txt="Informazioni"/>
    <str id="InstallPanel.headline" txt="Installazione"/>
    <str id="JDKPathPanel.headline" txt="Percorso JDK"/>
    <str id="LicencePanel.headline" txt="Accordo di Licenza"/>
    <str id="PacksPanel.headline" txt="Seleziona Pacchetti di Installazione"/>
    <str id="TreePacksPanel.headline" txt="Seleziona Pacchetti di Installazione"/>
    <str id="ProcessPanel.headline" txt="Esegui Processi Esterni"/>
    <str id="ShortcutPanel.headline" txt="Scorciatoia di Setup"/>
    <str id="SimpleFinishPanel.headline" txt="Installazione Completata"/>
    <str id="SummaryPanel.headline" txt="Riepilogo Dati di Configurazione"/>
    <str id="TargetPanel.headline" txt="Percorso di Destinazione"/>
    <str id="UserInputPanel.headline" txt="Dati Utente"/>
    <str id="UserPathPanel.headline" txt="Seleziona Percorso"/>
    <str id="InstallationGroupPanel.headline" txt="Gruppo di Installazione"/>
    <str id="InstallationTypePanel.headline" txt="Tipo di Installazione"/>

    <!-- General installer strings -->
    <str id="installer.title" txt="Installazione di "/>
    <str id="installer.reversetitle" txt="$APP_NAME $APP_VER - Procedura di Installazione"/>
    <str id="installer.next" txt="Avanti"/>
    <str id="installer.prev" txt="Indietro"/>
    <str id="installer.quit" txt="Esci"/>
    <str id="installer.madewith" txt="DCP Setup Maker/IzPack"/>
    <str id="installer.quit.title" txt="$APP_NAME $APP_VER"/>
    <str id="installer.quit.message" txt="Siete sicuri di voler annullare l'installazione?"/>
    <str id="installer.warning" txt="Avviso!"/>
    <str id="installer.yes" txt="Si"/>
    <str id="installer.no" txt="No"/>
    <str id="installer.cancel" txt="Annulla"/>
    <str id="installer.error" txt="Errore"/>
    <str id="installer.help" txt="Guida"/>
    <str id="installer.step" txt="Punto"/>
    <str id="installer.of" txt="di"/>
    <str id="installer.Message" txt="Messaggio"/>

    <!-- Uninstaller specific strings -->
    <str id="uninstaller.warning" txt="Questo rimuovera'  il programma installato!"/>
    <str id="uninstaller.destroytarget" txt=" Forza l'eliminazione di "/>
    <str id="uninstaller.uninstall" txt="Disinstalla"/>

    <!-- The strings for the 'official' IzPack plugins -->
    <!-- HelloPanel strings -->
    <str id="HelloPanel.welcome1" txt="Benvenuti nell'installazione di "/>
    <str id="HelloPanel.welcome2" txt="!"/>
    <str id="HelloPanel.authors" txt="Questo programma e' sviluppato da: "/>
    <str id="HelloPanel.url" txt="Il sito si trova qui: "/>

    <!-- LicensePanel strings -->
    <str id="LicencePanel.info" txt="Leggete attentamente il seguente accordo di licenza:"/>
    <str id="LicencePanel.agree" txt="Accetto i termini di questo accordo di licenza."/>
    <str id="LicencePanel.notagree" txt="Non accetto i termini di questo accordo di licenza."/>
    <str id="LicencePanel.yes" txt="Si"/>
    <str id="LicencePanel.no" txt="No"/>

		<!-- PrinterSelect Panel -->
		<str id="PrinterSelectPanel.select_printer" txt="Selezionate la stampante da usare per la configurazione iniziale e i test."/>

		<!-- InfoPanel strings -->
		<str id="InfoPanel.info" txt="Leggete le seguenti informazioni: "/>

		<!-- PathInputPanel strings -->
		<str id="PathInputPanel.required" txt="La cartella scelta dovrebbe esistere."/>
    <str id="PathInputPanel.required.forModificationInstallation" txt="La cartella scelta dovrebbe esistere."/>
    <str id="PathInputPanel.notValid" txt="La cartella scelta non contiene il prodotto richiesto."/>

		<!-- TargetPanel strings -->
    <str id="TargetPanel.info" txt="Selezionate il percorso di installazione: "/>
    <str id="TargetPanel.browse" txt="Sfoglia..."/>
    <str id="TargetPanel.warn" txt="La cartella esiste gia' ! Siete sicuri di voler installare qui e possibilmente sovrascrivere i file esistenti?"/>
    <str id="TargetPanel.empty_target" txt="Non avete specificato un percorso di destinazione! E' corretto?"/>
    <str id="TargetPanel.createdir" txt="La cartella di destinazione verra' creata: "/>
    <str id="TargetPanel.nodir" txt="Questo file non e' una cartella! Selezionate una cartella!"/>
    <str id="TargetPanel.notwritable" txt="Questa cartella non puo' essere scritta! Selezionate un'altra cartella!"/>

    <!-- JDKPathPanel strings -->
    <str id="JDKPathPanel.extendedIntro" txt="Il programma installato ha bisogno di un JDK tra la versione ${JDKPathPanel.minVersion} e la ${JDKPathPanel.maxVersion}. Un ambiente di esecuzione java (JRE) non sara' sufficiente."/>
    <str id="JDKPathPanel.intro" txt="Il programma installato ha bisogno di un JDK. Un ambiente di esecuzione java (JRE) non sara' sufficiente."/>
    <str id="JDKPathPanel.info" txt="Selezionate il percorso per il JDK:"/>
    <str id="JDKPathPanel.badVersion1" txt="Il JDK selezionato ha la versione errata (disponibile: "/>
    <str id="JDKPathPanel.badVersion2" txt=" richiesto: "/>
    <str id="JDKPathPanel.badVersion3" txt=") questo JDK dovrebbe essere usato comunque?"/>
    <str id="JDKPathPanel.nonValidPathInReg" txt="Il registro di Windows contiene un percorso non valido per questo JDK. Dovrebbe essere usato comunque?"/>

		<!-- PacksPanel strings -->
		<str id="PacksPanel.info" txt="Selezionate i pacchetti che volete installare:"/>
    <str id="PacksPanel.tip" txt="N.B: I pacchetti in grigio sono obbligatori."/>
    <str id="PacksPanel.space" txt="Spazio Richiesto in Totale: "/>
    <str id="PacksPanel.freespace" txt="Spazio Disponibile: "/>
    <str id="PacksPanel.description" txt="Descrizione"/>
    <str id="PacksPanel.dependencyList" txt="Il seguente pacchetto ha le seguenti dipendenze e/o esclusioni"/>
    <str id="PacksPanel.dependencies" txt="Dipendenze: "/>
    <str id="PacksPanel.excludes" txt="Esclusioni: "/>
    <str id="PacksPanel.notEnoughSpace" txt="Lo spazio su disco richiesto eccede lo spazio su disco disponibile."/>
    <str id="PacksPanel.notAscertainable" txt="non accertabile"/>
		
		<!-- InstallPanel strings -->
		<str id="InstallPanel.info" txt="Cliccate 'Installa!' per iniziare il processo di installazione"/>
    <str id="InstallPanel.install" txt="Installa!"/>
    <str id="InstallPanel.tip" txt="Avanzamento installazione Pacchetto:"/>
    <str id="InstallPanel.begin" txt=" "/>
    <str id="InstallPanel.finished" txt="[Completato]"/>
    <str id="InstallPanel.progress" txt="Avanzamento complessivo dell'installazione:"/>
    <str id="InstallPanel.overwrite.title" txt="Il file esiste gia'"/>
    <str id="InstallPanel.overwrite.question" txt="Il seguente file esiste gia'. Volete sovrascriverlo?"/>

		<!-- InstallationGroupPanel strings -->
		<str id="InstallationGroupPanel.colNameSelected" txt="Selezionato"/>
    <str id="InstallationGroupPanel.colNameInstallType" txt="InstallType"/>
    <str id="InstallationGroupPanel.colNameSize" txt="Dimensioni"/>
		
		<!-- InstallationTypePanel strings -->
    <str id="InstallationTypePanel.info" txt="Selezionate il tipo di installazione:"/>
    <str id="InstallationTypePanel.normal" txt="Nuova installazione"/>
    <str id="InstallationTypePanel.modify" txt="Modifica installazione"/>
		
		<!-- FinishPanel strings -->
		<str id="FinishPanel.success" txt="L'installazione e' stata completata correttamente."/>
    <str id="FinishPanel.done" txt="Finito"/>
    <str id="FinishPanel.fail" txt="L'installazione non e' stata completata!"/>
    <str id="FinishPanel.uninst.info" txt="E' stat creato un programma di disinstallazione e' stato creto in: "/>
    <str id="FinishPanel.auto" txt="Genera uno script di installazione automatica"/>
    <str id="FinishPanel.auto.tip" txt="Usa questo script per ripetere questa installazione su altri computer."/>
    <str id="FinishPanel.auto.dialog.filterdesc" txt="File XML"/>

		<!-- ImgPacksPanel strings -->
	<str id="ImgPacksPanel.dependencyList" txt="Dipendenze e/o esclusioni"/>
    <str id="ImgPacksPanel.packs" txt="Sono disponibili i seguenti pacchetti:"/>
    <str id="ImgPacksPanel.snap" txt="Immagine del pacchetto:"/>
    <str id="ImgPacksPanel.checkbox" txt=" Installa questo pacchetto"/>

    <!-- ShortcutPanel strings -->
    <str id="ShortcutPanel.regular.list" txt="Seleziona un Gruppo Programma per i collegamenti:"/>
    <str id="ShortcutPanel.regular.default" txt="Predefinito"/>
    <str id="ShortcutPanel.regular.desktop" txt="Crea collegamenti aggiuntivi sul desktop"/>
    <str id="ShortcutPanel.regular.create" txt="Crea collegamenti nel menu Start"/>
    <str id="ShortcutPanel.regular.userIntro" txt="crea collegamento per:"/>
    <str id="ShortcutPanel.regular.currentUser" txt="utente attuale"/>
    <str id="ShortcutPanel.regular.allUsers" txt="tutti gli utenti"/>
    <str id="ShortcutPanel.alternate.apology" txt="Ci dispiace ma IzPack non supporta la creazione di collegamenti su questo sistema operativo. Per creare i collegamenti, fate riferimento al manuale del vostro sistema operativo."/>
    <str id="ShortcutPanel.alternate.targetsLabel" txt="Il seguente e' un elenco di obiettivi ai quali il produttore di questo programma vuole che abbiate accesso."/>
